[book]
authors = ["Ch1n3du"]
language = "en"
multilingual = false
src = "src"


[output.html]
git-repository-url = "https://github.com/opshin"
git-repository-icon = "fa-github"
site-url = "/"

[output.html.fold]
enable = true
level = 0
